### ISSUE TITLE
Could not find type definition file for 'vite-plugin-vue-layouts/client'

### ISSUE THREAD

**Issue by yb3616** [JohnCampionJr/vite-plugin-vue-layouts#111]
## vscode
版本: 1.78.0 (user setup)
提交: 252e5463d60e63238250799aef7375787f68b4ee
日期: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
沙盒化: No

> vite.config.ts

![image](https://user-images.githubusercontent.com/8839021/236185474-397ca731-9c9c-4c45-a654-ceee03e66245.png)

> tsconfig.json

![image](https://user-images.githubusercontent.com/8839021/236185847-34f5c8a1-f7f6-48ac-9430-e2501769451c.png)

> main.ts

![image](https://user-images.githubusercontent.com/8839021/236186218-573bd0bc-5ff3-4e43-9f10-cb62fb69cfc3.png)

It's ok when I use `"vite-plugin-vue-layouts": "^0.3.0"`，but failed on `"vite-plugin-vue-layouts": "^0.8.0"`

**Comment by markthree** [comment]
@yb3616 

设置 client-types 👉 [vite-plugin-vue-layouts#client-types](https://github.com/JohnCampionJr/vite-plugin-vue-layouts#client-types)

set [client-types] 👉 [vite-plugin-vue-layouts#client-types](https://github.com/JohnCampionJr/vite-plugin-vue-layouts#client-types)

**Comment by yb3616** [comment]
> 

I've already do it

![image](https://user-images.githubusercontent.com/8839021/236433502-ece2a84b-9e70-4293-ae71-71d0a383c8af.png)

**Comment by FrankLin23** [comment]
I have some problems and I have already add client-types in `tsconfig.json` and `vite-env.d.ts`.

**Comment by Ardanas** [comment]
Has this problem been solved?

**Comment by markthree** [comment]
@Ardanas @FrankLin23 @yb3616 It's still in progress, you can temporarily use 👉 [vite-plugin-vue-meta-layouts](https://github.com/dishait/vite-plugin-vue-meta-layouts)。

Potentially related issue 👉 #112

**Comment by kkudr** [comment]
@markthree @Ardanas @FrankLin23 @yb3616

This problem is related to the [--resolvePackageJsonExports flag in TypeScript 5.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#resolvepackagejsonexports)

As written there, forces TypeScript to consult the exports field of package.json files **if it ever reads from a package in node_modules**.

To fix this, we need to add the following settings to the package.json file, as is done in [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages/blob/main/package.json#L32)

```
"exports": {
  "./client": {
    "types": "./client.d.ts"
  },
}
```

Temporary solutions:

1) Disable the --resolvePackageJsonExports flag 
2) Change the path in env.d.ts  from

`/// <reference types="vite-plugin-vue-layouts/client" />`

to

`/// <reference types="vite-plugin-vue-layouts/client.d.ts" />`

**Comment by serkodev** [comment]
@kkudr Thanks for the solution and find out the reason.

Another temporary solution is replacing `"vite-plugin-vue-layouts/client.d.ts"` to `"vite-plugin-vue-layouts/client"` in `tsconfig.json`.
```diff
{
  "compilerOptions": {
-    "types": ["vite-plugin-vue-layouts/client"]
+    "types": ["vite-plugin-vue-layouts/client.d.ts"]
  }
}
```

**Comment by andersonfelix** [comment]
Guys: https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/114#issuecomment-1665922024

**Comment by queee03** [comment]
A temporary solution, its work for me:
```
// tsconfig.json
{
  "compilerOptions": {
-    "moduleResolution": "Bundler"
+    "moduleResolution": "Node"
  }
}
```

**Comment by JohnCampionJr** [comment]
Will be fixed in next version.
