### ISSUE TITLE
Maybe there's something wrong with this regex?

### ISSUE THREAD

**Issue by l246804** [JohnCampionJr/vite-plugin-vue-layouts#124]
now:

```ts
/.?2/.test(5.2) // true
```

You can try this:
```ts
parseInt(info.version) === 2
```

https://github.com/JohnCampionJr/vite-plugin-vue-layouts/blob/b854833476f18667a374dbff3b1ba8877a6853ec/src/clientSide.ts#L12C1-L12C1

**Comment by markthree** [comment]
@l246804 Unfortunately, due to the release mechanism, these changes may not take effect, you may want to consider using [vite-plugin-vue-meta-layouts](https://github.com/dishait/vite-plugin-vue-meta-layouts/blob/main/README_EN.md) in the meantime. 

This has been fixed and re-released in this package

ref -> https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/112
