### ISSUE TITLE
Default layouts for different group of routes ?

### ISSUE THREAD

**Issue by rderimay** [JohnCampionJr/vite-plugin-vue-layouts#33]
I am searching a way to define a layout for a whole group of pages. For example, a part of my site is a blog based en vite-pages and your plugin with pages written in markdown. 

Having to put a `<router></router>` block on every md file is quite tedious and not very logical.
I feel I am missing some way to define the default layout to be used for a route and its children. 
Maybe I missed something in the documentation or maybe there is a simple way to make that happen. 
I already tried to change the routes (`router.getRoutes()`) on the fly by adding the need meta, but it had no effect. I presume the callback is too late in the chain.

Many thanks !

**Comment by ctholho** [comment]
If I remember correctly, there is a nested layout in both of the [examples](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/tree/main/examples).

If it's not: My hunch would be to create an `index.vue` at the `/subdir`-level in which you define the `<route>` block. Then all files at`subdir/*.md` would be displayed in this `<router-view />`. But that's mainly `vite-plugin-pages` magic. Because all this plugin does is wrap the normal `<router-view />` with another view.

**Comment by rderimay** [comment]
Thanks for your answer. I came up with this solution:
```
Pages({
    ...
     extendRoute(route, parent) {
         if (route.path.indexOf('/blog') === 0) {
            return {
                ...route,
                meta: { layout: '404' }
            }
        }
    }
    ...
})
```

Thanks for pointing to the pages plugin, I should have found this myself actually...
And thanks for this awesome plugin!

**Comment by ctholho** [comment]
I'm glad I could help. Also, please consider closing this issue.
