### ISSUE TITLE
Catch-all doesn't match / when using vite-plugin-vue-layouts

### ISSUE THREAD

**Issue by lewebsimple** [JohnCampionJr/vite-plugin-vue-layouts#4]
I'm using `pages/[...all].vue` to handle most of my top-level routes including `/` by having only this catch-all file and no `pages/index.vue` but it seems / will not match when vite-plugin-vue-layouts is enabled (it works just fine when I disable it)

I don't get any error in the console and I don't see any component in vue devtools where I normally see the page components (under RouterView).

Is this normal behaviour or am I missing something in the plugin options (I'm using none actually) ?

**Comment by JohnCampionJr** [comment]
Any chance of a repo?  Lot of moving parts to this.

**Comment by lewebsimple** [comment]
https://github.com/lewebsimple/vite-layouts-repro
Explanations in README.md

**Comment by ctholho** [comment]
I've been looking into this and I think the problem is that <router-view> isn't automatically resolved for dynamic route. I have a very limited understanding of all of this but I thougth this *should* work.

[Vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages/) uses a flat routes object. So the path of `/:all(.*)` is resolved as you would expect. But this plugin has one top-level component at the path `'/'` and all routes are then children of this top-level component. This is called [nested routes](https://router.vuejs.org/guide/essentials/nested-routes.html).

## To solve this on your end you could use
To fix it and have some resemblance of normality you could add this att the top level in your [...all].vue file.
```
<route lang="yaml">
alias: /
</route>
```

## What *could* be done?
Guarding for dynamic route matching and adding `alias: '/'` will solve the problem.
