### ISSUE TITLE
Pages render Twice

### ISSUE THREAD

**Issue by dsolay** [JohnCampionJr/vite-plugin-vue-layouts#6]
## Steps to reproduce

- Add a route block in page component
```
<route lang="yaml">
meta:
  layout: layout_name
</route>
```
- Put a `console.log('Hi! Render Page!!')` in setup method of component
-  See the message twice in the dev tools

![2021-03-13_09:15:17_950x1022](https://user-images.githubusercontent.com/22564820/111034789-d684c000-83dc-11eb-8f76-b8cefd570b2c.png)

This also heppen in the [vitasse](https://github.com/antfu/vitesse) starter template 

## Aditional context
Posible related to #4

**Comment by ZhaoZhao18** [comment]
Yes, I have also encountered this problem.
![image](https://user-images.githubusercontent.com/38499654/113683438-ca97cf80-96f6-11eb-9571-e7fe26829eb5.png)

**Comment by EngHell** [comment]
I want to add more input to this, it looks like the component is first rendered without the layout then the layout is loaded and this reload the component, you can check this by adding a console.log('layout setup') inside the layout setup function.

**Comment by husayt** [comment]
This must also be related to #11

**Comment by EngHell** [comment]
I applied the hotfix mentioned in of changing const name = ref('defualt') to const name = ref('') which fixes the fact that the default layout always renders, but then theres someting more happening when you change a page using vue router first the plugin changes the layout before even the navigation is triggered which causes the page component to be reload then vue router changes the page and the new page is rendered.
This probably need a new bug report.

**Comment by ctholho** [comment]
Well, the layout change happens before the route change. That's because right now a template update is triggered with a `beforeEach()` hook. So I throttled my connection speed which makes it very apparent.

The page is displayed while the template is already changed. And If you have a template already in cache and you need a while to load the page, it can become a bit wonky.

I applied the following and it *seems to fix it for me*. Please test this and see if everything works as expected.

In your `node_modules/vite-plugin-vue-layouts/dist/index.js` change these lines

(Line 72)
```diff
-    router.beforeEach(async (to, from, next) => {
-      await updateLayout(to.meta?.layout)
-      next()
+    router.afterEach((to, from) => {
+      updateLayout(to.meta?.layout)
    })
```

**Comment by 0SilentFox0** [comment]
So found that this bug still exists ( When I render the page the first time everything is good but when I change the route and return back it renders twice
<img width="530" alt="Screenshot 2023-04-24 at 17 15 36" src="https://user-images.githubusercontent.com/42321833/234023881-130a0713-df3d-494f-961e-800cf8bda273.png">
