### ISSUE TITLE
Unknown HTML tag route

### ISSUE THREAD

**Issue by tlerbao** [JohnCampionJr/vite-plugin-vue-layouts#80]
In the IDE of JetBrains, it will prompt: Unknown HTML tag route

Is there a solution to this?

Thanks for open source

<img width="417" alt="image" src="https://user-images.githubusercontent.com/20442232/197699070-253cf401-885a-4d0e-91e3-940bcd41d827.png">

**Comment by WebMechanic** [comment]
since this is not an official element within .vue SFC, I doubt JetBrains will add support.
You can always add unknown tags as custom HTML tags via the 💡 pop up menu: "Add route to custom elements"  and maybe follow up with "Inject language" to get YAML syntax support inside. 
However that setting does not persist afaik.
see File | Settings | Editor | Inspections -> HTML for your custom elements.

happens to me if I use `<some-element>` in .html files, too

**Comment by tlerbao** [comment]
@WebMechanic  Thanks, that's what I do now .
